
server:
  port: 10007

# Logging configuration
log:
  collectionName: LinkShortLog

# Security settings
security:
  ignored: /**/public

mongo:
  spring:
    uri: mongodb://localhost:27017/linkShortner?retryWrites=true&w=majority