
server:
  port: 10007

# Logging configuration
log:
  collectionName: LinkShortLog

# Security settings
security:
  ignored: /**/public


spring:
  application:
    name: URL-SHORT-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost


base:
  url: https://shortener.guardianservices.in/

